apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: et-app
  name: et-app
  namespace: app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: et-app
  template:
    metadata:
      labels:
        app: et-app
    spec:
      containers:
        - image: 'hpkns/spinnaker-demo:${HashCommit}'
          name: et-app
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: et-app-service
  namespace: app-dev
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30100
      protocol: TCP
  selector:
    app: et-app
  type: LoadBalancer
