apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: et-app
  name: et-app
  namespace: '${trigger.parameters["Env"]}'
spec:
  replicas: 4
  selector:
    matchLabels:
      app: et-app
  template:
    metadata:
      labels:
        app: et-app
    spec:
      containers:
        - image: 'hpkns/spinnaker-demo:${trigger.parameters["HashCommit"]}'
          name: et-app
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: et-app-sevice
  name: et-app-service
  namespace: '${trigger.parameters["Env"]}'
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30100
      protocol: TCP
  selector:
    app: et-app
  type: NodePort
