apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    traffic.spinnaker.io/load-balancers: '["service et-app-service"]'
    strategy.spinnaker.io/max-version-history: '2'
  name: et-app
  namespace: '${trigger.parameters["Env"]}'
  labels:
    app: et-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: et-app
  template:
    metadata:
      labels:
        app: et-app
    spec:
      containers:
        - image: 'hpkns/spinnaker-demo:${trigger.parameters["HashCommit"]}'
          name: et-app
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: et-app-service
  namespace: app-dev
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30100
      protocol: TCP
  selector:
    app: et-app
  type: NodePort
