apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    traffic.spinnaker.io/load-balancers: '["service et-app-service"]'
    strategy.spinnaker.io/max-version-history: '2'
  name: et-app
  namespace: app-dev
  labels:
    app-name: et-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app-name: et-app
  template:
    metadata:
      labels:
        app-name: et-app
    spec:
      containers:
        - image: 'hpkns/spinnaker-demo:9a45274a3d7c267861815be8f9f3f12f1bfa65bf'
          name: et-app
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: et-app-service
  namespace: app-dev
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30100
      protocol: TCP
  selector:
    app: et-app
  type: NodePort
